#!/usr/bin/env python3
"""Build src/fonts.css by base64-embedding the Tajawal TTFs in assets/fonts/.

Why base64 and not a Google Fonts <link>: headless Chromium stalls on remote
font fetches and rasterizes Arabic as tofu boxes (□). Embedding the font in the
CSS makes the render fully offline and deterministic.

Run once after downloading the fonts (see README). Re-run only if the fonts change.
"""
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FONTS = [
    ("Tajawal", 400, "assets/fonts/Tajawal-Regular.ttf"),
    ("Tajawal", 500, "assets/fonts/Tajawal-Medium.ttf"),
    ("Tajawal", 700, "assets/fonts/Tajawal-Bold.ttf"),
    ("Tajawal", 800, "assets/fonts/Tajawal-ExtraBold.ttf"),
]

HEADER = (
    "/* fonts.css — Tajawal embedded as Base64 (offline, headless-safe).\n"
    "   Generated by scripts/build-fonts.py from assets/fonts/*.ttf.\n"
    "   Remote font loads stall headless Chromium and produce tofu boxes —\n"
    "   never link Google Fonts here. */\n"
)


def main() -> int:
    chunks = [HEADER]
    for family, weight, rel in FONTS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print(f"missing font: {rel}", file=sys.stderr)
            return 1
        with open(path, "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode("ascii")
        chunks.append(
            "@font-face{\n"
            f"  font-family:'{family}';\n"
            "  font-style:normal;\n"
            f"  font-weight:{weight};\n"
            "  font-display:block;\n"
            f"  src:url(data:font/ttf;base64,{b64}) format('truetype');\n"
            "}\n"
        )
    out_path = os.path.join(ROOT, "src", "fonts.css")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(chunks))
    print(f"wrote {out_path} ({os.path.getsize(out_path)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
